const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * fmt 11.0.2 (pinned by react-native 0.76) unconditionally enables `consteval`
 * compile-time format-string checking on Apple clang 16+/Xcode 16+ (incl. clang
 * 21 / Xcode 26). That clang then rejects fmt's own format calls inside the
 * consteval context, breaking the iOS Pods build with:
 *   "call to consteval function ... is not a constant expression"
 *
 * base.h `#define`s FMT_USE_CONSTEVAL with no `#ifndef` guard, so passing
 * -DFMT_USE_CONSTEVAL=0 via build settings gets clobbered. The only reliable fix
 * is to patch the header to force the macro off (falls back to constexpr/runtime
 * format validation — no runtime behavior change). fmt 11.1+ fixes this upstream,
 * but RN pins 11.0.2.
 *
 * The patch runs in the Podfile `post_install` hook (the only point where the
 * downloaded Pods/fmt sources exist). Delivered as a config plugin because
 * apps/mobile/ios is gitignored / regenerated by `expo prebuild`, which would
 * otherwise wipe a raw Podfile edit.
 */
const MARKER = 'FMT_USE_CONSTEVAL_FIX';
const SNIPPET = `
    # withFmtConstevalFix: patch fmt 11.0.2 to disable consteval (Apple clang 16+/Xcode 16+ bug)
    fmt_base_h = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base_h)
      contents = File.read(fmt_base_h)
      unless contents.include?('${MARKER}')
        contents = contents.sub(
          "#if FMT_USE_CONSTEVAL\\n",
          "// ${MARKER}: forced off for Apple clang 16+/Xcode 16+\\n" \\
          "#undef FMT_USE_CONSTEVAL\\n#define FMT_USE_CONSTEVAL 0\\n#if FMT_USE_CONSTEVAL\\n"
        )
        File.chmod(0644, fmt_base_h)
        File.write(fmt_base_h, contents)
        Pod::UI.puts '[withFmtConstevalFix] patched fmt base.h to disable consteval'
      end
    end
`;

module.exports = function withFmtConstevalFix(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfile, 'utf8');

      if (!contents.includes(MARKER)) {
        const anchor = 'post_install do |installer|\n';
        const idx = contents.indexOf(anchor);
        if (idx === -1) {
          throw new Error('withFmtConstevalFix: could not find post_install block in Podfile');
        }
        const insertAt = idx + anchor.length;
        contents = contents.slice(0, insertAt) + SNIPPET + contents.slice(insertAt);
        fs.writeFileSync(podfile, contents);
      }

      return cfg;
    },
  ]);
};
